; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=constraint-elimination -constraint-elimination-divrem-coefficients -S %s | FileCheck %s

; =====================================================================
; sdiv coefficient-based constraints: q = sdiv x, n (constant n > 0)
;   From x = q*n + r, |r| < n:
;     n*q - n < x < n*q + n
; =====================================================================

; If x >=s 6 and q = sdiv x, 3, then q >=s 2 (because 3*q > x - 3 >= 3, so q > 1)
define i1 @sdiv_lower_bound(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_lower_bound(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[X]], 6
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], 3
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sge i32 %x, 6
  br i1 %cmp, label %mid, label %else

mid:
  %q = sdiv i32 %x, 3
  %v = icmp sge i32 %q, 2
  ret i1 %v

else:
  ret i1 false
}

; If q = sdiv x, 2 and q <s 10, then x <s 22 (because x < 2*q + 2 <= 22)
define i1 @sdiv_upper_bound(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_upper_bound(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[Q]], 10
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %q = sdiv i32 %x, 2
  %cmp = icmp slt i32 %q, 10
  br i1 %cmp, label %mid, label %else

mid:
  %v = icmp slt i32 %x, 22
  ret i1 %v

else:
  ret i1 false
}

; Also provable: x < 20 from q < 10 (since x < 2*9 + 2 = 20)
define i1 @sdiv_tighter_upper_bound(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_tighter_upper_bound(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[Q]], 10
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %q = sdiv i32 %x, 2
  %cmp = icmp slt i32 %q, 10
  br i1 %cmp, label %mid, label %else

mid:
  %v = icmp slt i32 %x, 20
  ret i1 %v

else:
  ret i1 false
}

; Negative: can't prove x < 19 from q < 10 (x could be 19, q = 9)
define i1 @sdiv_upper_bound_neg(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_upper_bound_neg(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[Q]], 10
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[V:%.*]] = icmp slt i32 [[X]], 19
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %q = sdiv i32 %x, 2
  %cmp = icmp slt i32 %q, 10
  br i1 %cmp, label %mid, label %else

mid:
  %v = icmp slt i32 %x, 19
  ret i1 %v

else:
  ret i1 false
}

; sdiv with negative x: if x <=s -4 and q = sdiv x, 2, then q <=s -1
; (because 2*q < x + 2 <= -2, so q < -1, i.e. q <= -1... wait:
;  x <=s -4 means x <= -4. q = sdiv x, 2 rounds toward 0.
;  sdiv(-4, 2) = -2, sdiv(-5, 2) = -2. So q <= -2.
;  We want q <=s -1, which is weaker and should be provable.)
define i1 @sdiv_negative_x(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_negative_x(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[X]], -4
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], 2
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sle i32 %x, -4
  br i1 %cmp, label %mid, label %else

mid:
  %q = sdiv i32 %x, 2
  %v = icmp sle i32 %q, -1
  ret i1 %v

else:
  ret i1 false
}

; srem with constant n > 0: |srem(x, n)| < n regardless of x's sign.
; So srem(x, 5) >=s -4 is always true.
define i1 @srem_abs_bound(i32 noundef %x) {
; CHECK-LABEL: define i1 @srem_abs_bound(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = srem i32 %x, 5
  %v = icmp sge i32 %r, -4
  ret i1 %v
}

; srem(x, 5) <s 5 is always true.
define i1 @srem_upper_bound(i32 noundef %x) {
; CHECK-LABEL: define i1 @srem_upper_bound(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    ret i1 true
;
entry:
  %r = srem i32 %x, 5
  %v = icmp slt i32 %r, 5
  ret i1 %v
}

; Negative: srem(x, 5) <s 4 is NOT always true (could be 4).
define i1 @srem_upper_bound_neg(i32 noundef %x) {
; CHECK-LABEL: define i1 @srem_upper_bound_neg(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[V:%.*]] = icmp slt i32 [[R]], 4
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = srem i32 %x, 5
  %v = icmp slt i32 %r, 4
  ret i1 %v
}

; Negative: srem(x, 5) >=s -3 is NOT always true (could be -4).
define i1 @srem_lower_bound_neg(i32 noundef %x) {
; CHECK-LABEL: define i1 @srem_lower_bound_neg(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    [[V:%.*]] = icmp sge i32 [[R]], -3
; CHECK-NEXT:    ret i1 [[V]]
;
entry:
  %r = srem i32 %x, 5
  %v = icmp sge i32 %r, -3
  ret i1 %v
}

; =====================================================================
; sdiv exact: q = sdiv exact x, n  ==>  x = n*q  (tighter than |r| < n)
; =====================================================================

; sdiv exact gives tighter upper bound than non-exact.
; q = sdiv exact x, 2, q <s 10 => x <s 20 (exact: x = 2*q < 20)
; Compare with sdiv_tighter_upper_bound which also proves this,
; but sdiv exact can also prove x <s 19 — which non-exact cannot.
define i1 @sdiv_exact_tight_upper(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_exact_tight_upper(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Q:%.*]] = sdiv exact i32 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[Q]], 10
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %q = sdiv exact i32 %x, 2
  %cmp = icmp slt i32 %q, 10
  br i1 %cmp, label %mid, label %else

mid:
  ; x = 2*q, q <= 9, so x <= 18 < 19
  %v = icmp slt i32 %x, 19
  ret i1 %v

else:
  ret i1 false
}

; Negative: sdiv exact x, 2 with q <s 10 cannot prove x <s 18.
; x = 2*q, q <= 9, so x <= 18. x <s 18 is NOT provable.
define i1 @sdiv_exact_tight_upper_neg(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_exact_tight_upper_neg(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Q:%.*]] = sdiv exact i32 [[X]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[Q]], 10
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[V:%.*]] = icmp slt i32 [[X]], 18
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %q = sdiv exact i32 %x, 2
  %cmp = icmp slt i32 %q, 10
  br i1 %cmp, label %mid, label %else

mid:
  %v = icmp slt i32 %x, 18
  ret i1 %v

else:
  ret i1 false
}

; sdiv exact from quotient to dividend, negative direction.
; q = sdiv exact x, 3, q <=s -2 => x <=s -6 (x = 3*(-2) = -6)
define i1 @sdiv_exact_negative(i32 noundef %x) {
; CHECK-LABEL: define i1 @sdiv_exact_negative(
; CHECK-SAME: i32 noundef [[X:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[Q:%.*]] = sdiv exact i32 [[X]], 3
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[Q]], -2
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %q = sdiv exact i32 %x, 3
  %cmp = icmp sle i32 %q, -2
  br i1 %cmp, label %mid, label %else

mid:
  ; x = 3*q, q <= -2, so x <= -6
  %v = icmp sle i32 %x, -6
  ret i1 %v

else:
  ret i1 false
}

; Chained: srem(x, 5) <s 5, and 5 <s m, so srem(x, 5) <s m
define i1 @srem_chain_with_bound(i32 noundef %x, i32 noundef %m) {
; CHECK-LABEL: define i1 @srem_chain_with_bound(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[M:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[M]], 5
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], 5
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %cmp = icmp sgt i32 %m, 5
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, 5
  %v = icmp slt i32 %r, %m
  ret i1 %v

else:
  ret i1 false
}
