; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

; x >=s 0  /\  n >=s 0  /\  n <s m  /\  r = srem x, n  ==>  r <s n <s m  ==>  r <s m
define i1 @srem_slt_divisor_bound(i32 noundef %x, i32 noundef %n, i32 noundef %m) {
; CHECK-LABEL: define i1 @srem_slt_divisor_bound(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[M:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB2:%.*]], label [[ELSE]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[N]], [[M]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb2, label %else

bb2:
  %cmp = icmp slt i32 %n, %m
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp slt i32 %r, %m
  ret i1 %v

else:
  ret i1 false
}

; x >=s 0  /\  n >=s 0  /\  n <=s m  /\  r = srem x, n  ==>  r <s n <=s m  ==>  r <=s m
define i1 @srem_sle_divisor_bound(i32 noundef %x, i32 noundef %n, i32 noundef %m) {
; CHECK-LABEL: define i1 @srem_sle_divisor_bound(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[M:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB2:%.*]], label [[ELSE]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[N]], [[M]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb2, label %else

bb2:
  %cmp = icmp sle i32 %n, %m
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp sle i32 %r, %m
  ret i1 %v

else:
  ret i1 false
}

; x >=s 0  /\  x <=s limit  /\  r = srem x, n  ==>  r <=s x <=s limit
define i1 @srem_sle_dividend_bound(i32 noundef %x, i32 noundef %n, i32 noundef %limit) {
; CHECK-LABEL: define i1 @srem_sle_dividend_bound(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[LIMIT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[X]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %cmp = icmp sle i32 %x, %limit
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp sle i32 %r, %limit
  ret i1 %v

else:
  ret i1 false
}

; x >=s 0  /\  n >=s 0  /\  x <=s limit  /\  q = sdiv x, n  ==>  q <=s x <=s limit
define i1 @sdiv_sle_dividend_bound(i32 noundef %x, i32 noundef %n, i32 noundef %limit) {
; CHECK-LABEL: define i1 @sdiv_sle_dividend_bound(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[LIMIT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB2:%.*]], label [[ELSE]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[X]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb2, label %else

bb2:
  %cmp = icmp sle i32 %x, %limit
  br i1 %cmp, label %mid, label %else

mid:
  %q = sdiv i32 %x, %n
  br label %check

check:
  %v = icmp sle i32 %q, %limit
  ret i1 %v

else:
  ret i1 false
}

; Chained: x >=s 0  /\  n >=s 0  /\  n <s m  /\  m <s k  /\  r = srem x, n  ==>  r <s k
define i1 @srem_chain_three_hops(i32 noundef %x, i32 noundef %n, i32 noundef %m, i32 noundef %k) {
; CHECK-LABEL: define i1 @srem_chain_three_hops(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[M:%.*]], i32 noundef [[K:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB0:%.*]], label [[OUT:%.*]]
; CHECK:       bb0:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB1:%.*]], label [[OUT]]
; CHECK:       bb1:
; CHECK-NEXT:    [[C1:%.*]] = icmp slt i32 [[N]], [[M]]
; CHECK-NEXT:    br i1 [[C1]], label [[BB2:%.*]], label [[OUT]]
; CHECK:       bb2:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    [[C2:%.*]] = icmp slt i32 [[M]], [[K]]
; CHECK-NEXT:    br i1 [[C2]], label [[BB3:%.*]], label [[OUT]]
; CHECK:       bb3:
; CHECK-NEXT:    ret i1 true
; CHECK:       out:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb0, label %out

bb0:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb1, label %out

bb1:
  %c1 = icmp slt i32 %n, %m
  br i1 %c1, label %bb2, label %out

bb2:
  %r = srem i32 %x, %n
  %c2 = icmp slt i32 %m, %k
  br i1 %c2, label %bb3, label %out

bb3:
  %v = icmp slt i32 %r, %k
  ret i1 %v

out:
  ret i1 false
}

; Both sdiv and srem with combined constraints.
define i1 @sdiv_srem_combined(i32 noundef %x, i32 noundef %n, i32 noundef %limit) {
; CHECK-LABEL: define i1 @sdiv_srem_combined(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[LIMIT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    [[AND0:%.*]] = and i1 [[X_POS]], [[N_POS]]
; CHECK-NEXT:    br i1 [[AND0]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[N]], [[LIMIT]]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sle i32 [[X]], [[LIMIT]]
; CHECK-NEXT:    [[AND:%.*]] = and i1 [[CMP1]], [[CMP2]]
; CHECK-NEXT:    br i1 [[AND]], label [[THEN:%.*]], label [[ELSE]]
; CHECK:       then:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], [[N]]
; CHECK-NEXT:    [[RES:%.*]] = and i1 true, true
; CHECK-NEXT:    ret i1 [[RES]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  %n_pos = icmp sge i32 %n, 0
  %and0 = and i1 %x_pos, %n_pos
  br i1 %and0, label %bb1, label %else

bb1:
  %cmp1 = icmp slt i32 %n, %limit
  %cmp2 = icmp sle i32 %x, %limit
  %and = and i1 %cmp1, %cmp2
  br i1 %and, label %then, label %else

then:
  %r = srem i32 %x, %n
  %q = sdiv i32 %x, %n
  %cmp3 = icmp sle i32 %r, %limit
  %cmp4 = icmp sle i32 %q, %limit
  %res = and i1 %cmp3, %cmp4
  ret i1 %res

else:
  ret i1 false
}

; i64 type
define i1 @srem_i64(i64 noundef %x, i64 noundef %n, i64 noundef %m) {
; CHECK-LABEL: define i1 @srem_i64(
; CHECK-SAME: i64 noundef [[X:%.*]], i64 noundef [[N:%.*]], i64 noundef [[M:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i64 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i64 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB2:%.*]], label [[ELSE]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[N]], [[M]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i64 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i64 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %n_pos = icmp sge i64 %n, 0
  br i1 %n_pos, label %bb2, label %else

bb2:
  %cmp = icmp slt i64 %n, %m
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i64 %x, %n
  br label %check

check:
  %v = icmp slt i64 %r, %m
  ret i1 %v

else:
  ret i1 false
}

; Negative: srem without noundef on the srem operands.
define i1 @neg_srem_no_noundef(i32 noundef %x, i32 %n, i32 noundef %m) {
; CHECK-LABEL: define i1 @neg_srem_no_noundef(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 [[N:%.*]], i32 noundef [[M:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB2:%.*]], label [[ELSE]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[N]], [[M]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    [[V:%.*]] = icmp slt i32 [[R]], [[M]]
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb2, label %else

bb2:
  %cmp = icmp slt i32 %n, %m
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp slt i32 %r, %m
  ret i1 %v

else:
  ret i1 false
}

; Negative: sdiv without noundef.
define i1 @neg_sdiv_no_noundef(i32 noundef %x, i32 %n, i32 noundef %limit) {
; CHECK-LABEL: define i1 @neg_sdiv_no_noundef(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 [[N:%.*]], i32 noundef [[LIMIT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB2:%.*]], label [[ELSE]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[X]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    [[V:%.*]] = icmp sle i32 [[Q]], [[LIMIT]]
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb2, label %else

bb2:
  %cmp = icmp sle i32 %x, %limit
  br i1 %cmp, label %mid, label %else

mid:
  %q = sdiv i32 %x, %n
  br label %check

check:
  %v = icmp sle i32 %q, %limit
  ret i1 %v

else:
  ret i1 false
}

; Negative: x might be negative — can't derive srem facts.
define i1 @neg_srem_x_might_be_negative(i32 noundef %x, i32 noundef %n, i32 noundef %m) {
; CHECK-LABEL: define i1 @neg_srem_x_might_be_negative(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[M:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[N_POS:%.*]] = icmp sge i32 [[N]], 0
; CHECK-NEXT:    br i1 [[N_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[N]], [[M]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    [[V:%.*]] = icmp slt i32 [[R]], [[M]]
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %n_pos = icmp sge i32 %n, 0
  br i1 %n_pos, label %bb1, label %else

bb1:
  %cmp = icmp slt i32 %n, %m
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp slt i32 %r, %m
  ret i1 %v

else:
  ret i1 false
}

; Negative: sdiv with only x non-negative, n might be negative.
define i1 @neg_sdiv_n_might_be_negative(i32 noundef %x, i32 noundef %n, i32 noundef %limit) {
; CHECK-LABEL: define i1 @neg_sdiv_n_might_be_negative(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[LIMIT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[X]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[Q:%.*]] = sdiv i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    [[V:%.*]] = icmp sle i32 [[Q]], [[LIMIT]]
; CHECK-NEXT:    ret i1 [[V]]
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %cmp = icmp sle i32 %x, %limit
  br i1 %cmp, label %mid, label %else

mid:
  %q = sdiv i32 %x, %n
  br label %check

check:
  %v = icmp sle i32 %q, %limit
  ret i1 %v

else:
  ret i1 false
}

; srem: x >=s 0 only (n not known non-negative) — result >=s 0 and <=s x still hold
define i1 @srem_nonneg_dividend_only(i32 noundef %x, i32 noundef %n, i32 noundef %limit) {
; CHECK-LABEL: define i1 @srem_nonneg_dividend_only(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]], i32 noundef [[LIMIT:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[BB1:%.*]], label [[ELSE:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sle i32 [[X]], [[LIMIT]]
; CHECK-NEXT:    br i1 [[CMP]], label [[MID:%.*]], label [[ELSE]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %bb1, label %else

bb1:
  %cmp = icmp sle i32 %x, %limit
  br i1 %cmp, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp sle i32 %r, %limit
  ret i1 %v

else:
  ret i1 false
}

; srem result is non-negative when x is non-negative
define i1 @srem_result_nonneg(i32 noundef %x, i32 noundef %n) {
; CHECK-LABEL: define i1 @srem_result_nonneg(
; CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[N:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X_POS:%.*]] = icmp sge i32 [[X]], 0
; CHECK-NEXT:    br i1 [[X_POS]], label [[MID:%.*]], label [[ELSE:%.*]]
; CHECK:       mid:
; CHECK-NEXT:    [[R:%.*]] = srem i32 [[X]], [[N]]
; CHECK-NEXT:    br label [[CHECK:%.*]]
; CHECK:       check:
; CHECK-NEXT:    ret i1 true
; CHECK:       else:
; CHECK-NEXT:    ret i1 false
;
entry:
  %x_pos = icmp sge i32 %x, 0
  br i1 %x_pos, label %mid, label %else

mid:
  %r = srem i32 %x, %n
  br label %check

check:
  %v = icmp sge i32 %r, 0
  ret i1 %v

else:
  ret i1 false
}
